export enum ResourceType {
  Energy = 1,
  Silver = 2,

  ClassicArenaToken = 3,

  Gems = 4,

  GoldBar = 5,
  TagArenaToken = 6,

  PotionLesserMagic = 101,
  PotionGreaterMagic = 102,
  PotionSuperiorMagic = 103,
  PotionLesserForce = 111,
  PotionGreaterForce = 112,
  PotionSuperiorForce = 113,
  PotionLesserSpirit = 121,
  PotionGreaterSpirit = 122,
  PotionSuperiorSpirit = 123,
  PotionLesserVoid = 131,
  PotionGreaterVoid = 132,
  PotionSuperiorVoid = 133,
  PotionLesserArcane = 141,
  PotionGreaterArcane = 142,
  PotionSuperiorArcane = 143,

  ArenaMedalBronze = 201,
  ArenaMedalSilver = 202,
  ArenaMedalGold = 203,

  ClanBossKey = 300,

  FactionKeyBannerLords = 501,
  FactionKeyHighElves = 502,
  FactionKeySacredOrder = 503,
  FactionKeyCircleOfMagi = 504,
  FactionKeyOgrynTribes = 505,
  FactionKeyLizardmen = 506,
  FactionKeySkinwalkers = 507,
  FactionKeyOrcs = 508,
  FactionKeyDemonspawn = 509,
  FactionKeyUndeadHordes = 510,
  FactionKeyDarkElves = 511,
  FactionKeyKnightRevenant = 512,
  FactionKeyBarbarians = 513,
  FactionKeyNyresanElf = 514,
  FactionKeyShadowKin = 515,
  FactionKeyDwarves = 516,

  ForgeMaterialMagisteel = 601,
  ForgeMaterialCorehammer = 602,
  ForgeMaterialRareSoulstone = 611,
  ForgeMaterialEpicSoulstone = 612,
  ForgeMagerialLegendarySoulstone = 613,
  ForgeMaterialRareBloodstone = 621,
  ForgeMaterialEpicBloodstone = 622,
  ForgeMaterialLegendaryBloodstone = 623,
  ForgeMaterialRareNetherEgg = 631,
  ForgeMaterialEpicNetherEgg = 632,
  ForgeMaterialLegendaryNetherEgg = 633,
  ForgeMaterialRareScarabClaw = 641,
  ForgeMaterialEpicScarabClaw = 642,
  ForgeMaterialLegendaryScarabClaw = 643,
  ForgeMaterialRareMagmaCore = 651,
  ForgeMaterialEpicMagmaCore = 652,
  ForgeMaterialLegendaryMagmaCore = 653,
  ForgeMaterialRareFrostSpine = 661,
  ForgeMaterialEpicFrostSpine = 662,
  ForgeMaterialLegendaryFrostSpine = 663,
  ForgeMaterialRareDragonBone = 671,
  ForgeMaterialEpicDragonBone = 672,
  ForgeMaterialLegendaryDragonBone = 673,
  ForgeMaterialRareGriffinFeather = 681,
  ForgeMaterialEpicGriffinFeather = 682,
  ForgeMaterialLegendaryGriffinFeather = 683,

  DoomTowerGoldKey = 700,
  DoomTowerSilverKey = 701,
}
